package org.aoclient.network.protocol.command.metadata;

import java.util.List;

/**
 * Representa un comando del juego. Cada comando contiene un nombre, una descripcion y una lista de argumentos. Estos comandos
 * pueden ser ejecutados por jugadores o administradores (GM) dependiendo de la configuracion.
 * <p>
 * La convencion estandar de los argumentos es: <> = requerido, [] = opcional
 */

public enum GameCommand {

    // ==================== USER COMMANDS ====================
    BALANCE("/balance", "Check your account balance", List.of()),
    BET("/bet", "Gamble gold with gambler NPC", List.of("<amount>")),
    BUG("/bug", "Report a bug to administrators", List.of("<description>")),
    CLEAR("/clear", "Clean the console", List.of()),
    CONSULTATION("/consultation", "Make a consultation request", List.of()),
    COUNCIL_MSG("/councilmsg", "Send message to council members", List.of("<message>")),
    DEPOSIT_GOLD("/depositgold", "Deposit gold in the bank", List.of("<amount>")),
    DESC("/desc", "Change your character description", List.of("<description>")),
    ENLIST("/enlist", "Enlist in faction army", List.of()),
    EXTRACT_GOLD("/extractgold", "Extract gold from the bank", List.of("<amount>")),
    GM("/gm", "Request help from Game Master", List.of()),
    GUILD_FOUND("/guildfound", "Found a new guild", List.of("<guild_name>")),
    GUILD_LEAVE("/guildleave", "Leave the guild", List.of()),
    GUILD_MSG("/guildmsg", "Send message to guild members", List.of("<message>")),
    GUILD_ONLINE("/guildonline", "Show online guild members", List.of()),
    GUILD_VOTE("/guildvote", "Vote in guild elections", List.of("<player>")),
    HEAL("/heal", "Heal other players", List.of()),
    HELP("/?", "Show available commands", List.of()),
    INFORMATION("/information", "Get server information", List.of()),
    LEAVE_FACTION("/leavefaction", "Leave current faction", List.of()),
    MEDITATE("/meditate", "Meditate to recover mana", List.of()),
    MOTD("/motd", "Show message of the day", List.of()),
    ONLINE("/online", "Show online players count", List.of()),
    OPEN_BANK("/openbank", "Open bank interface", List.of()),
    PARTY_ACCEPT("/partyaccept", "Accept player into party", List.of("<player>")),
    PARTY_CREATE("/partycreate", "Create a party", List.of()),
    PARTY_JOIN("/partyjoin", "Join or request to join a party", List.of()),
    PARTY_KICK("/partykick", "Kick member from party", List.of("<player>")),
    PARTY_LEAVE("/partyleave", "Leave the party", List.of()),
    PARTY_MSG("/partymsg", "Send message to party members", List.of("<message>")),
    PARTY_ONLINE("/partyonline", "Show online party members", List.of()),
    PARTY_SET_LEADER("/partysetleader", "Transfer party leadership", List.of("<player>")),
    PET_FOLLOW("/petfollow", "Make your pet follow you", List.of()),
    PET_RELEASE("/petrelease", "Release your pet", List.of()),
    PET_STAY("/petstay", "Make your pet stay in place", List.of()),
    POLL("/poll", "Participate in server polls", List.of("<option>")),
    QUIT("/quit", "Quit the game safely", List.of()),
    REPORT("/report", "Report a player for misconduct", List.of("<player>", "<reason>")),
    REST("/rest", "Rest to recover stamina", List.of()),
    RESURRECT("/resurrect", "Resurrect other players", List.of()),
    REWARD("/reward", "Claim daily reward", List.of()),
    ROL("/rol", "Request role master assistance", List.of("<message>")),
    SENTINEL_CODE("/sentinelcode", "Submit sentinel verification code", List.of("<code>")),
    SHARE_NPC("/sharenpc", "Share NPC with other players", List.of()),
    STATS("/stats", "Show your character statistics", List.of()),
    STOP_SHARING_NPC("/stopsharingnpc", "Stop sharing NPC", List.of()),
    TRADE("/trade", "Start trading with NPC", List.of()),
    TRAIN_LIST("/train", "Show available creatures to train", List.of()),
    UPTIME("/uptime", "Show server uptime", List.of()),
    // ==================== GM COMMANDS ====================
    ACCEPT_CHAOS_COUNCIL("/acceptchaoscouncil", "Accept chaos council member", List.of("<player>")),
    ACCEPT_ROYAL_COUNCIL("/acceptroyalcouncil", "Accept royal council member", List.of("<player>")),
    ADMIN_SERVER("/adminserver", "Toggle server for administrators", List.of()),
    ALTERNATE_PASSWORD("/alternatepassword", "Copy password between players", List.of("<player_without_password>", "<player_with_password>")),
    BACKUP("/backup", "Create server backup", List.of()),
    BAN("/ban", "Ban a player", List.of("<player>", "<reason>")),
    BAN_IP("/banip", "Ban IP address or player", List.of("<ip|nick>", "<reason>")),
    BAN_IP_LIST("/baniplist", "Show list of banned IP addresses", List.of()),
    BAN_IP_RELOAD("/banipreload", "Reload banned IP list", List.of()),
    BLOCK_TILE("/blocktile", "Block the tile of the current position", List.of()),
    CHANGE_EMAIL("/changeemail", "Change player's email address", List.of("<player>", "<email>")),
    CHANGE_MOTD("/motdchange", "Change message of the day", List.of()),
    CHANGE_NICK("/changenick", "Change player's name", List.of("<nick>", "<new_nick>")),
    CHAOS_ARMOUR("/chaosarmour", "Give chaos faction armor", List.of("<armor>", "<object>")),
    CHAOS_MSG("/chaosmsg", "Send message to chaos legion", List.of("<message>")),
    CHAT_COLOR("/chatcolor", "Change chat text color", List.of("<r>", "<g>", "<b>")),
    CITIZEN_MSG("/citizenmsg", "Send message to all citizens", List.of("<message>")),
    CLEAN_NPC_INV("/cleannpcinv", "Clean NPC inventory", List.of()),
    CLEAN_SOS("/cleansos", "Clear SOS message list", List.of()),
    CLEAN_WORLD("/clean", "Clean world objects", List.of()),
    COMMENT_SERVER_LOG("/rem", "Add comment to server log", List.of("<comment>")),
    CREATE_NPC("/createnpc", "Create NPC at current location", List.of("<npc_id>")),
    CREATE_NPC_RESPAWN("/createnpcrespawn", "Create respawning NPC", List.of("<npc_id>")),
    CREATE_OBJ("/createobj", "Create object at current location", List.of("<obj_id>")),
    CREATE_TELEPORT("/createteleport", "Create teleport at location", List.of("<map>", "<x>", "<y>", "[radiu]")),
    CRIMINAL_MSG("/criminalsmsg", "Send message to all criminals", List.of("<message>")),
    DUMP_SECURITY("/dumpsecurity", "Dump security IP tables", List.of()),
    DUMB("/dumb", "Make player unable to speak", List.of("<player>")),
    FORGIVE("/forgive", "Forgive player's crimes", List.of("<player>")),
    GM_MSG("/gmmsg", "Send global GM message", List.of("<message>")),
    GM_PANEL("/gmpanel", "Open GM panel", List.of()),
    GUILD_BAN("/guildban", "Ban a guild", List.of("<guild>")),
    GUILD_KICK("/guildkick", "Kick member from guild", List.of("<player>")),
    GUILD_MEMBERS("/guildmembers", "Show guild member list", List.of("<guild>")),
    GUILD_MESSAGES("/guildmessages", "Show guild message history", List.of("<guild>")),
    GUILD_ONLINE_SPECIFIC("/guildonlinespecific", "Show online members of specific guild", List.of("<guild>")),
    HOME("/home", "Return to home city", List.of()),
    IMPERIAL_ARMOUR("/imperialarmour", "Give imperial faction armor", List.of("<armor_id>", "<object_id>")),
    INVISIBILITY("/invisibility", "Toggle invisibility", List.of()),
    IP_TO_NICK("/iptonick", "Get nick from IP address", List.of("<ip>")),
    JAIL("/jail", "Send player to jail", List.of("<player>", "<reason>", "<minutes>")),
    KICK("/kick", "Kick player from server", List.of("<player>")),
    KICK_ALL("/kickall", "Kick all players from server", List.of()),
    KICK_COUNCIL("/kickcouncil", "Remove player from council", List.of("<player>")),
    KILL("/kill", "Mata a un player", List.of("<player>")),
    LAST_IP("/lastip", "Show player's last IP address", List.of("<player>")),
    MOB_PANEL("/mobpanel", "Open Mob panel", List.of()),
    MOD_MAP("/modmap", "Modify map properties", List.of("<option>", "<value>")),
    MOD_PLAYER("/modplayer", "Modify player properties", List.of("<player>", "<property>", "<value>", "[extra_param]")),
    NAVIGATION("/navigation", "Toggle navigation", List.of()),
    NICK_TO_IP("/nicktoip", "Get IP address from nickname", List.of("<nick>")),
    NIGHT("/night", "Change time to night", List.of()),
    NO_DUMB("/nodumb", "Restore player's ability to speak", List.of("<player>")),
    NPC_FOLLOW("/npcfollow", "Make NPC follow you", List.of()),
    ONLINE_CHAOS("/onlinechaos", "Show online chaos legion members", List.of()),
    ONLINE_GM("/onlinegm", "Show online game masters", List.of()),
    ONLINE_MAP("/onlinemap", "Show players online in specific map", List.of("<map>")),
    ONLINE_ROYAL("/onlineroyal", "Show online royal army members", List.of()),
    PING("/ping", "Check server connection latency", List.of()),
    PLAYER_BANK("/playerbank", "Show player bank", List.of("<player>")),
    PLAYER_EMAIL("/playeremail", "Show player email", List.of("<player>")),
    PLAYER_GOLD("/playergold", "Show player gold", List.of("<player>")),
    PLAYER_INFO("/playerinfo", "Show player info", List.of("<player>")),
    PLAYER_INV("/playerinv", "Show player inventory", List.of("<player>")),
    PLAYER_LOCATION("/playerlocation", "Show player location", List.of("<player>")),
    PLAYER_SKILLS("/playerskills", "Show player skills", List.of("<player>")),
    PLAYER_SLOT("/playerslot", "Show player inventory slot", List.of("<player>", "<slot>")),
    PLAYER_STATS("/playerstats", "Show player stats", List.of("<player>")),
    PLAY_MUSIC("/playmusic", "Play music", List.of("<music_id>", "[map]")),
    PLAY_SOUND("/playsound", "Play sound", List.of("<sound_id>", "[map]", "[x]", "[y]")),
    RAIN("/rain", "Toggle rain", List.of()),
    RELOAD_NPC("/reloadnpc", "Reload npcs", List.of()),
    RELOAD_OBJ("/reloadobj", "Reload objects", List.of()),
    RELOAD_SERVER_INI("/reloadserverini", "Reload server ini settings", List.of()),
    RELOAD_SPELL("/reloadspell", "Reload spells", List.of()),
    REMOVE_ARMY("/removearmy", "Remove player from royal army", List.of("<player>")),
    REMOVE_CHAOS("/removechaos", "Remove player from chaos legion", List.of("<player>")),
    REMOVE_FACTIONS("/removefactions", "Remove player from all factions", List.of("<player>")),
    REMOVE_ITEM("/removeitem", "Remove item in current location", List.of()),
    REMOVE_ITEM_AREA("/removeitemarea", "Remove items in area", List.of()),
    REMOVE_NPC("/removenpc", "Remove npc", List.of()),
    REMOVE_NPC_AREA("/removenpcarea", "Remove npcs in area", List.of()),
    REMOVE_NPC_NO_RESPAWN("/removenpcnorespawn", "Remove npc without respawn", List.of()),
    REMOVE_PUNISHMENT("/removepunishment", "Remove player punishment", List.of("<player>")),
    REMOVE_TELEPORT("/removeteleport", "Remove selected teleport", List.of()),
    AUTO_UPDATE("/autoupdate", "Reset autoupdate system", List.of()),
    RESTART("/restart", "Restart the server", List.of()),
    REVIVE("/revive", "Revive a player", List.of("<player>")),
    RMSG("/rmsg", "Send message to all players", List.of("<message>")),
    ROYAL_ARMY_MSG("/royalarmymsg", "Send message to royal army", List.of("<message>")),
    SAVE_CHAR("/savechar", "Save all character data", List.of()),
    SAVE_MAP("/savemap", "Save current map", List.of()),
    SENTINEL("/sentinel", "Toggle sentinel", List.of()),
    SET_DESC("/setdesc", "Set player description", List.of("<player>", "<description>")),
    SETINIVAR("/setinivar", "Set server configuration variable", List.of("<llave>", "<clave>", "<valor>")),
    SHOW("/show", "Show server information panels", List.of("<SOS|INT>")),
    SHOW_HIDDEN("/showhidden", "Show hidden players", List.of()),
    SHOW_IGNORED("/showignored", "Show ignored players list", List.of()),
    SHOW_MOBS("/showmobs", "Show mobs in specific map", List.of("<map>")),
    SHOW_NAME("/showname", "Toggle name display above characters", List.of()),
    SHOW_OBJ_MAP("/showobjmap", "Show objets in current map", List.of()),
    SHOW_WORKERS("/showworkers", "Show working players", List.of()),
    SHUTDOWN("/shutdown", "Shutdown server", List.of()),
    SILENCE("/silent", "Silence a player", List.of("<player>")),
    SUMMON("/summon", "Summon player to your location", List.of("<player>")),
    SYSTEM_MESSAGE("/systemmsg", "Send system message", List.of("<message>")),
    TALK_AS_NPC("/talkas", "Speak as npc character", List.of("<message>")),
    TELEPORT("/teleport", "Teleport player to location", List.of("[nick]", "[map]", "<x>", "<y>")),
    TELEPORT_NEAR_TO_PLAYER("/teleportneartoplayer", "Teleport near specified player", List.of("<player>")),
    TELEPORT_TO_PLAYER("/teleporttoplayer", "Teleport to player", List.of("<player>")),
    TELEPORT_TO_TARGET("/teleporttotarget", "Teleport to target", List.of()),
    TIME("/time", "Show current server time", List.of()),
    TRIGGER("/trigger", "Set or check map trigger", List.of("<trigger>")),
    TURN_CRIMINAL("/turncriminal", "Turn player into criminal", List.of("<player>")),
    UNBAN("/unban", "Unban a player", List.of("<player>")),
    UNBAN_IP("/unbanip", "Unban an IP address", List.of("<ip>")),
    WARNING("/warning", "Send warning to player", List.of("<player>", "<reason>"));

    private final String command;
    private final String description;
    private final List<String> arguments;

    GameCommand(String command, String description, List<String> arguments) {
        this.command = command;
        this.description = description;
        this.arguments = List.copyOf(arguments);
    }

    public String getCommand() {
        return command;
    }

    public String getDescription() {
        return description;
    }

    public List<String> getArguments() {
        return arguments;
    }

}
