package org.aoclient.engine.game;

public enum E_KeyType {
    mKeyUp,
    mKeyDown,
    mKeyLeft,
    mKeyRight,
    mKeyToggleMusic,
    mKeyToggleSound,
    mKeyToggleFxs,
    mKeyRequestRefresh,
    mKeyToggleNames,
    mKeyGetObject,
    mKeyEquipObject,
    mKeyTamAnimal,
    mKeySteal,
    mKeyToggleSafeMode,
    mKeyToggleResuscitationSafe,
    mKeyHide,
    mKeyDropObject,
    mKeyUseObject,
    mKeyAttack,
    mKeyTalk,
    mKeyTalkWithGuild,
    mKeyTakeScreenShot,
    mKeyShowOptions,
    mKeyMeditate,
    mKeyCastSpellMacro,
    mKeyWorkMacro,
    mKeyExitGame,
}
